# Generated by Django 3.0.3 on 2020-03-07 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=32, verbose_name='Country State')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countrystate_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countrystate_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Country State',
                'verbose_name_plural': 'Country States',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=32, verbose_name='Municipality')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipality_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('country_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', related_query_name='municipalities', to='topology.CountryState')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipality_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=32, verbose_name='Parish')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parish_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishes', related_query_name='parish', to='topology.Municipality')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parish_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Parish',
                'verbose_name_plural': 'Parishes',
                'ordering': ('name',),
            },
        ),
    ]
